### ISSUE TITLE
Dchess for android

### ISSUE THREAD

**Issue by khuttur** [defenchess/Defenchess#24]
Hello sir,

It seems that dchess is very strong now, so
 
Would you please provide me an android version of defenchess?

Thanks!

**Comment by defenchess** [comment]
Unfortunately I have no experience with Android and I also don't own any Android devices to be able to verify that my compile worked.

**Comment by Dogacel** [comment]
I can try compiling Defenchess on Android.

**Comment by khuttur** [comment]
It will awesome.
Please compile for android as soon as possible.

**Comment by khuttur** [comment]
Sir Dogacel,

Please compile defenchess for android.
Thanks!!!

**Comment by Dogacel** [comment]
@khuttur Sorry but couldn't make it work. I won't try impleneting Defenchess on Android in the near future.
